export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const ARTISTS = 'ARTISTS';
export const ARTIST_DETAILS = 'ARTIST_DETAILS';
export const SONGS = 'SONGS';
export const SONG_DETAILS = 'SONG_DETAILS';
export const NEW_GAME = 'NEW_GAME';

export const REQUEST_SUCCESS_ARTISTS = `REQUEST_SUCCESS_${ARTISTS}`;
export const REQUEST_SUCCESS_ARTIST_DETAILS = `REQUEST_SUCCESS_${ARTIST_DETAILS}`;
export const REQUEST_SUCCESS_SONGS = `REQUEST_SUCCESS_${SONGS}`;
export const REQUEST_SUCCESS_SONG_DETAILS = `REQUEST_SUCCESS_${SONG_DETAILS}`;
export const REQUEST_SUCCESS_NEW_GAME = `REQUEST_SUCCESS_${NEW_GAME}`;
