export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const ARTISTS = 'ARTISTS';
export const ARTIST_DETAILS = 'ARTIST_DETAILS';
export const SONGS = 'SONGS';
export const SONG_DETAILS = 'SONG_DETAILS';

export const REQUEST_SUCCESS_ARTISTS = 'REQUEST_SUCCESS_ARTISTS';
export const REQUEST_SUCCESS_ARTIST_DETAILS = 'REQUEST_SUCCESS_ARTIST_DETAILS';
export const REQUEST_SUCCESS_SONGS = 'REQUEST_SUCCESS_SONGS';
export const REQUEST_SUCCESS_SONG_DETAILS = 'REQUEST_SUCCESS_SONG_DETAILS';
