export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const ARTISTS = 'ARTISTS';
export const ARTIST_DETAILS = 'ARTIST_DETAILS';
export const SONGS = 'SONGS';
export const SONG_DETAILS = 'SONG_DETAILS';
export const NEW_GAME = 'NEW_GAME';
export const PSEUDO = 'PSEUDO';

export const REQUEST_SUCCESS_ARTISTS = `REQUEST_SUCCESS_${ARTISTS}`;
export const REQUEST_SUCCESS_ARTIST_DETAILS = `REQUEST_SUCCESS_${ARTIST_DETAILS}`;
export const REQUEST_SUCCESS_SONGS = `REQUEST_SUCCESS_${SONGS}`;
export const REQUEST_SUCCESS_SONG_DETAILS = `REQUEST_SUCCESS_${SONG_DETAILS}`;
export const REQUEST_SUCCESS_NEW_GAME = `REQUEST_SUCCESS_${NEW_GAME}`;
export const REQUEST_SUCCESS_PSEUDO = `REQUEST_SUCCESS_${PSEUDO}`;
export const REQUEST_SUCCESS_LOGIN = `REQUEST_SUCCESS_${LOGIN}`;

export const ADD_ARTIST_ID = 'ADD_ARTIST_ID';
export const ADD_PLAYER = 'ADD_PLAYER';

export const INIT_SOCKET_IO = 'INIT_SOCKET_IO';
